# Generated by Django 4.2.17 on 2025-01-05 20:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Requirement', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Need', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rescuecenter',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rescuecenter',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='rescuecenter',
            name='location',
        ),
        migrations.AddField(
            model_name='animal',
            name='adoption_fee',
            field=models.CharField(choices=[('FREE', 'Free'), ('LOW', '£1-£100'), ('MEDIUM', '£101-£250'), ('HIGH', '£251-£500'), ('PREMIUM', '£500+')], default='LOW', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='age_category',
            field=models.CharField(choices=[('BABY', 'Baby (0-1 year)'), ('YOUNG', 'Young (1-3 years)'), ('ADULT', 'Adult (3-8 years)'), ('SENIOR', 'Senior (8+ years)')], default='ADULT', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 5, 20, 27, 5, 483588, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='animal',
            name='energy_level',
            field=models.CharField(choices=[('LOW', 'Low Energy'), ('MODERATE', 'Moderate Energy'), ('HIGH', 'High Energy'), ('VERY_HIGH', 'Very High Energy')], default='MODERATE', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='foster_status',
            field=models.CharField(choices=[('NEEDED', 'Foster Home Needed'), ('TEMP', 'Temporary Foster Only'), ('LONG_TERM', 'Long-term Foster Needed'), ('NOT_NEEDED', 'Foster Not Required')], default='NOT_NEEDED', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='home_check',
            field=models.CharField(choices=[('REQUIRED', 'Home Check Required'), ('VIRTUAL', 'Virtual Home Check Accepted'), ('COMPLETED', 'Home Check Completed'), ('NOT_REQUIRED', 'No Home Check Required')], default='REQUIRED', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='postcode',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='reactivity',
            field=models.CharField(blank=True, choices=[('DOG_FRIENDLY', 'Good with Dogs'), ('CAT_FRIENDLY', 'Good with Cats'), ('CHILD_FRIENDLY', 'Good with Children'), ('STRANGER_FRIENDLY', 'Good with Strangers'), ('LEASH_REACTIVE', 'Leash Reactive'), ('RESOURCE_GUARD', 'Resource Guards')], default='DOG_FRIENDLY', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='training_level',
            field=models.CharField(choices=[('NONE', 'No Training'), ('BASIC', 'Basic Training'), ('INTERMEDIATE', 'Intermediate Training'), ('ADVANCED', 'Advanced Training')], default='BASIC', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='transport_available',
            field=models.CharField(choices=[('PROVIDED', 'Transport Available'), ('LOCAL_ONLY', 'Local Collection Only'), ('ARRANGED', 'Transport Can Be Arranged'), ('NOT_AVAILABLE', 'No Transport Available')], default='LOCAL_ONLY', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='urgency_status',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency - Immediate Placement Needed'), ('URGENT', 'Urgent - Within 7 Days'), ('SOON', 'Soon - Within 30 Days'), ('STANDARD', 'Standard - No Immediate Rush')], default='STANDARD', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='address',
            field=models.TextField(default='Address pending'),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='email',
            field=models.EmailField(default='pending@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='emergency_intake',
            field=models.CharField(choices=[('24_7', '24/7 Emergency Intake'), ('LIMITED', 'Limited Emergency Intake'), ('SCHEDULED', 'Scheduled Intake Only'), ('NONE', 'No Emergency Intake')], default='SCHEDULED', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='facilities',
            field=models.CharField(choices=[('KENNEL', 'Kennel Facilities'), ('CATTERY', 'Cattery'), ('STABLES', 'Stables'), ('VET', 'Veterinary Clinic'), ('TRAINING', 'Training Facilities'), ('REHAB', 'Rehabilitation Center')], default='KENNEL', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='foster_network',
            field=models.CharField(choices=[('ACTIVE', 'Active Foster Network'), ('LIMITED', 'Limited Foster Network'), ('NEEDED', 'Foster Homes Needed'), ('NONE', 'No Foster Network')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='home_check_radius',
            field=models.IntegerField(default=20, help_text='Maximum distance (in miles) for home checks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='phone',
            field=models.CharField(default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='postcode',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='rescue_type',
            field=models.CharField(choices=[('ALL', 'All Animals'), ('DOG', 'Dogs Only'), ('CAT', 'Cats Only'), ('HORSE', 'Horses/Farm Animals'), ('EXOTIC', 'Exotic Animals'), ('WILDLIFE', 'Wildlife')], default='ALL', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='services',
            field=models.CharField(choices=[('ADOPTION', 'Adoption Services'), ('FOSTERING', 'Fostering Program'), ('REHABILITATION', 'Rehabilitation'), ('TRAINING', 'Training Services'), ('MEDICAL', 'Medical Services'), ('BOARDING', 'Boarding Services'), ('BEHAVIOR', 'Behavioral Support'), ('TRANSPORT', 'Transport Services')], default='ADOPTION', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='transport_radius',
            field=models.CharField(choices=[('LOCAL', 'Local (up to 10 miles)'), ('REGIONAL', 'Regional (up to 50 miles)'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='LOCAL', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RABBIT', 'Rabbit'), ('HORSE', 'Horse'), ('BIRD', 'Bird'), ('SMALL_ANIMAL', 'Small Animal')], default='DOG', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='no.email@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Unnamed Contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='No phone provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='rescuecenter',
            name='name',
            field=models.CharField(default='Unnamed Center', max_length=200),
        ),
        migrations.AddField(
            model_name='animal',
            name='living_requirements',
            field=models.ManyToManyField(blank=True, to='rescue.livingrequirement'),
        ),
        migrations.AddField(
            model_name='animal',
            name='special_needs',
            field=models.ManyToManyField(blank=True, to='rescue.specialneed'),
        ),
    ]
