# Generated by Django 4.2.17 on 2025-06-26 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_animal_rescue_centre_centreimage_animalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='background',
            field=models.TextField(default='No background provided'),
        ),
        migrations.AddField(
            model_name='animal',
            name='bird_type',
            field=models.CharField(blank=True, choices=[('PARROT', 'Parrot'), ('BUDGIE', 'Budgie'), ('COCKATIEL', 'Cockatiel'), ('CANARY', 'Canary'), ('FINCH', 'Finch'), ('DOVE', 'Dove'), ('CHICKEN', 'Chicken'), ('DUCK', 'Duck'), ('OTHER', 'Other Bird')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='coat_length',
            field=models.CharField(choices=[('SHORT', 'Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long'), ('HAIRLESS', 'Hairless')], default='SHORT', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='colour',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='good_with',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='long_stay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='reptile_type',
            field=models.CharField(blank=True, choices=[('SNAKE', 'Snake'), ('BEARDED_DRAGON', 'Bearded Dragon'), ('IGUANA', 'Iguana'), ('TERRAPIN', 'Terrapin'), ('OTHER', 'Other Reptile')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='small_animal_type',
            field=models.CharField(blank=True, choices=[('GUINEA_PIG', 'Guinea Pig'), ('MOUSE', 'Mouse'), ('RAT', 'Rat'), ('HAMSTER', 'Hamster'), ('GERBIL', 'Gerbil'), ('OTHER', 'Other Small Animal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='special_needs_flag',
            field=models.BooleanField(default=False, verbose_name='Special Needs (simple yes/no)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperament',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RABBIT', 'Rabbit'), ('HORSE', 'Horse or Pony'), ('SMALL_ANIMAL', 'Small Animal'), ('BIRD', 'Bird'), ('REPTILE', 'Reptile'), ('OTHER', 'Other')], default='DOG', max_length=20),
        ),
    ]
