# Generated by Django 4.2.17 on 2025-01-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='living_requirements',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='special_needs',
        ),
        migrations.DeleteModel(
            name='RescueCenter',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='LivingRequirement',
        ),
        migrations.DeleteModel(
            name='SpecialNeed',
        ),
    ]
