# Generated by Django 4.2.17 on 2025-01-05 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RescueCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rescue_type', models.CharField(choices=[('ALL', 'All Animals'), ('DOG', 'Dogs Only'), ('CAT', 'Cats Only'), ('HORSE', 'Horses/Farm Animals'), ('EXOTIC', 'Exotic Animals'), ('WILDLIFE', 'Wildlife')], max_length=50)),
                ('services', models.CharField(choices=[('ADOPTION', 'Adoption Services'), ('FOSTERING', 'Fostering Program'), ('REHABILITATION', 'Rehabilitation'), ('TRAINING', 'Training Services'), ('MEDICAL', 'Medical Services'), ('BOARDING', 'Boarding Services'), ('BEHAVIOR', 'Behavioral Support'), ('TRANSPORT', 'Transport Services')], max_length=50)),
                ('facilities', models.CharField(choices=[('KENNEL', 'Kennel Facilities'), ('CATTERY', 'Cattery'), ('STABLES', 'Stables'), ('VET', 'Veterinary Clinic'), ('TRAINING', 'Training Facilities'), ('REHAB', 'Rehabilitation Center')], max_length=50)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('transport_radius', models.CharField(choices=[('LOCAL', 'Local (up to 10 miles)'), ('REGIONAL', 'Regional (up to 50 miles)'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], max_length=50)),
                ('foster_network', models.CharField(choices=[('ACTIVE', 'Active Foster Network'), ('LIMITED', 'Limited Foster Network'), ('NEEDED', 'Foster Homes Needed'), ('NONE', 'No Foster Network')], max_length=50)),
                ('emergency_intake', models.CharField(choices=[('24_7', '24/7 Emergency Intake'), ('LIMITED', 'Limited Emergency Intake'), ('SCHEDULED', 'Scheduled Intake Only'), ('NONE', 'No Emergency Intake')], max_length=50)),
                ('home_check_radius', models.IntegerField(help_text='Maximum distance (in miles) for home checks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RABBIT', 'Rabbit'), ('HORSE', 'Horse'), ('BIRD', 'Bird'), ('SMALL_ANIMAL', 'Small Animal')], max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age_category', models.CharField(choices=[('BABY', 'Baby (0-1 year)'), ('YOUNG', 'Young (1-3 years)'), ('ADULT', 'Adult (3-8 years)'), ('SENIOR', 'Senior (8+ years)')], max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=50)),
                ('description', models.TextField()),
                ('energy_level', models.CharField(choices=[('LOW', 'Low Energy'), ('MODERATE', 'Moderate Energy'), ('HIGH', 'High Energy'), ('VERY_HIGH', 'Very High Energy')], max_length=50)),
                ('training_level', models.CharField(choices=[('NONE', 'No Training'), ('BASIC', 'Basic Training'), ('INTERMEDIATE', 'Intermediate Training'), ('ADVANCED', 'Advanced Training')], max_length=50)),
                ('reactivity', models.CharField(blank=True, choices=[('DOG_FRIENDLY', 'Good with Dogs'), ('CAT_FRIENDLY', 'Good with Cats'), ('CHILD_FRIENDLY', 'Good with Children'), ('STRANGER_FRIENDLY', 'Good with Strangers'), ('LEASH_REACTIVE', 'Leash Reactive'), ('RESOURCE_GUARD', 'Resource Guards')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('adoption_fee', models.CharField(choices=[('FREE', 'Free'), ('LOW', '£1-£100'), ('MEDIUM', '£101-£250'), ('HIGH', '£251-£500'), ('PREMIUM', '£500+')], max_length=50)),
                ('home_check', models.CharField(choices=[('REQUIRED', 'Home Check Required'), ('VIRTUAL', 'Virtual Home Check Accepted'), ('COMPLETED', 'Home Check Completed'), ('NOT_REQUIRED', 'No Home Check Required')], max_length=50)),
                ('transport_available', models.CharField(choices=[('PROVIDED', 'Transport Available'), ('LOCAL_ONLY', 'Local Collection Only'), ('ARRANGED', 'Transport Can Be Arranged'), ('NOT_AVAILABLE', 'No Transport Available')], max_length=50)),
                ('urgency_status', models.CharField(choices=[('EMERGENCY', 'Emergency - Immediate Placement Needed'), ('URGENT', 'Urgent - Within 7 Days'), ('SOON', 'Soon - Within 30 Days'), ('STANDARD', 'Standard - No Immediate Rush')], max_length=50)),
                ('foster_status', models.CharField(choices=[('NEEDED', 'Foster Home Needed'), ('TEMP', 'Temporary Foster Only'), ('LONG_TERM', 'Long-term Foster Needed'), ('NOT_NEEDED', 'Foster Not Required')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('living_requirements', models.ManyToManyField(blank=True, to='hello_world.livingrequirement')),
                ('special_needs', models.ManyToManyField(blank=True, to='hello_world.specialneed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
